//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf2dubik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.HistoryImplementations = new HashSet<HistoryImplementations>();
            this.PointSale = new HashSet<PointSale>();
        }
    
        public int IDАгента { get; set; }
        public string НаименованиеКомпании { get; set; }
        public string ТипАгента { get; set; }
        public string ЮридическийАдрес { get; set; }
        public Nullable<int> ИНН { get; set; }
        public Nullable<int> КПП { get; set; }
        public string ФиоДиректора { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public byte[] Логотип { get; set; }
        public Nullable<int> Приоритет { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryImplementations> HistoryImplementations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointSale> PointSale { get; set; }
    }
}
