//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf2dubik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public int IDПоставки { get; set; }
        public int IDПоставщика { get; set; }
        public int IDСотрудника { get; set; }
        public Nullable<System.DateTime> ДатаПоставки { get; set; }
        public Nullable<int> КолМатериала { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
